version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 803928384365.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 803928384365.dkr.ecr.ap-northeast-1.amazonaws.com/python:latest .
      - docker tag 803928384365.dkr.ecr.ap-northeast-1.amazonaws.com/python:latest 803928384365.dkr.ecr.ap-northeast-1.amazonaws.com/python:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 803928384365.dkr.ecr.ap-northeast-1.amazonaws.com/python:latest
  
artifacts:
  files: Imagedefinitions.json
